HIPE 0161: generic token proposal
hyperledger/indy-hipe pull request #160
Opened 2020-09-17 23:25 UTC by lynnbendixsen

Signed-off-by: Lynn Bendixsen <lynn@indicio.tech>

I would like to submit for proposal a generic payment method.

2020-09-18 21:57 UTC, brentzundel requested changes

2020-09-18 21:57 UTC, brentzundel commented on text/0161-generic-token/README.md
> +- Author: [Lynn Bendixsen](lynn@indicio.tech)
```suggestion
- Authors: [Brent Zundel](brent.zundel@evernym.com), [Lynn Bendixsen](lynn@indicio.tech)
```

2020-09-18 21:57 UTC, brentzundel commented on text/0161-generic-token/README.md
> +- LibTokToken, which handles generic token payment functionality through the Indy-SDK payments API for the Token and Fees ledger plugins and produces properly formatted and signed transaction request
LibSovToken was a terrible name. I highly recommend not copying too closely here.
```suggestion
- LibIndyToken, which handles generic token payment functionality through the Indy-SDK payments API for the Token and Fees ledger plugins and produces properly formatted and signed transaction requests for each of the new transactions listed above. LibIndyToken also parses the transaction responses from the new ledger plugins through the Indy-SDK payments API.
```

2020-09-18 21:57 UTC, brentzundel commented on text/0161-generic-token/README.md
> +An example of the structure of the inputs and outputs of the LibTokToken payment handler plugin for the Indy-SDK payments API are documented here: [Token specific data structures.](https://github.com
```suggestion
An example of the structure of the inputs and outputs of the LibIndyToken payment handler plugin for the Indy-SDK payments API are documented here: [Token specific data structures.](https://github.com/sovrin-foundation/libsovtoken/blob/master/doc/data_structures.md) (from LibIndyToken's predecessor LibSovToken)
```

2020-09-18 21:57 UTC, brentzundel commented on text/0161-generic-token/README.md
> +This proposal was inspired by the Sovrin Token and its associated [SIP](https://github.com/sovrin-foundation/sovrin-sip/tree/master/text/5003-sovrin-tokens).
```suggestion
This proposal is a generic form of the Sovrin Token, made suitable for use by any Indy ledger, and the text is primarily taken from the associated [SIP](https://github.com/sovrin-foundation/sovrin-sip/tree/master/text/5003-sovrin-tokens). 
```

2020-09-18 21:57 UTC, brentzundel commented on text/0161-generic-token/README.md
> +Hyperledger Indy provides the code base for Indy ledgers. This code base may be extended with plugins. Ledger plugins add new transactions and sub-ledgers to the transactions and sub-ledgers already
```suggestion
Hyperledger Indy provides the code base for Indy ledgers. This code base may be extended with plugins. Ledger plugins add new transactions and sub-ledgers to the transactions and sub-ledgers already defined by Hyperledger Indy. This document introduces plugins for generic token transactions, which may be incorporated into any Indy ledger.
```

2020-09-18 21:57 UTC, brentzundel commented on text/0161-generic-token/README.md
> +Moving from an Endorser model, where trusted entities can submit write transaction to the ledger, to a Token model, where submitting a write transaction requires the payment of fees denominated in ge
```suggestion
Moving from an Endorser model, where trusted entities can submit write transaction to the ledger, to a Token model, where submitting a write transaction requires the payment of fees denominated in generic tokens, will likely introduce new costs to those who are currently trusted entities, unless the Auth rules are formulated to explicitly support both models.
```

2020-09-18 21:57 UTC, brentzundel commented on text/0161-generic-token/README.md
> +outside of the scope of this effort:
some additional questions it may be worthwhile to consider:
```suggestion
outside of the scope of this effort:
- Should fees paid to the ledger remain there (i.e., fees represent spent tokens), or should they be collected (i.e., fees represent tokens paid to an entity)?
- If the fees are to be collected by some entity, how is it determined what entity should collect them?
- What mechanism should be used to collect fees paid to the ledger? An automatic or a manual one?
- How might fees paid to the ledger be automatically distributed among participating validator nodes?
```

2020-09-22 21:14 UTC, lynnbendixsen commented on text/0161-generic-token/README.md
> +
```suggestion

This document proposes optional payment and fees plugins that enable any Indy ledger to support a token. 
```

2020-09-22 21:22 UTC, lynnbendixsen commented on text/0161-generic-token/README.md
> +
```suggestion
### A common API
Providing a common API for all Indy tokens will enable better wallet support. A wallet that supports a single Indy token could support any Indy token.
```

2020-09-25 20:43 UTC, brentzundel commented on text/0161-generic-token/README.md
> +
```suggestion

- **COLLECT_FEES** - Collects previously uncollected fees accumulated on the ledger, according
to the Auth_Rules. Each fee payment that has been recorded to the ledger, but not yet included
in a **COLLECT_FEES** transaction will be collected and deposited into the single specified
payment address. The **COLLECT_FEES** transaction records the transaction number of the first
fee transaction included in the current deposit and always collects all subsequent fees for
transactions up to the time of this **COLLECT_FEES** transaction.
```

2020-09-25 21:09 UTC, brentzundel commented on text/0161-generic-token/README.md
> +
```suggestion

As an alternative to the COLLECT_FEES transaction, it may be possible to
relegate the collection of fees to the FEE transaction itself, in conjunction
with an addition to the config ledger which specifies the payment address
to which fees should be sent. The assignment of this payment address
could be specified as its own transaction, as an addition to the SET_FEES
transaction, or as an addition to the MINT_PUBLIC transaction (e.g., reclaim
paid fees to the original minting address). The benefits of this alternative
over the COLLECT_FEES transaction include improved auditability, but the
drawbacks include potential negative performance impacts and a possibly
unmanageable number of small payments accumulated in the destination
payment address, so this alternative was deemed unviable at this time.

Another alternative to the COLLECT_FEES transaction is to never collect fees.
The safeguards against ledger attacks remain, but the tokens spent as fees
would be unrecoverable. It is possible to mimic this scenario by constituting
the ledger Auth_Rules such that the COLLECT_FEES transaction may not be called.


```

2020-09-28 21:32 UTC, dhh1128 commented
I am okay with merging this now. However, did you want to socialize this on a community call, @lynnbendixsen ?

2020-09-29 13:37 UTC, lynnbendixsen commented
> did you want to socialize this on a community call, @lynnbendixsen ?

I am on the agenda to present this for the Oct 12 Indy Contributors call. (Today's schedule for that call was already full).

2020-10-01 17:58 UTC, lynnbendixsen commented
@dhh1128 Are you able to merge this now, or were you planning to wait until after the community call?

2020-10-01 18:34 UTC, brentzundel commented on text/0161-generic-token/README.md
> +   - **FEES**
```suggestion
   - **GET_FEES**
   - **SET_FEES**
   - **FEES**
   - **COLLECT_FEES**
   - **UNCOLLECTED_FEES**
```

2020-10-01 18:36 UTC, brentzundel commented on text/0161-generic-token/README.md
> +Documentation for the proper format of transaction requests and transaction responses for the Fees plugin, specifically for the **SET_FEES**, **GET_FEES**, and **FEES** transactions can be found here
```suggestion
Documentation for the proper format of transaction requests and transaction
responses for the Fees plugin, specifically for the **SET_FEES**, **GET_FEES**,
**FEES**, **COLLECT_FEES**, and **UNCOLLECTED_FEES** transactions can be
found here: [Ledger Fee Transactions.](TODO: add link)
```

2020-10-01 22:23 UTC, dhh1128 commented
I am willing to merge it, but I understood your comment about the community call to be a request for me to wait. Has the PR at least been announced publicly (e.g., on #indy in Hyperledger RocketChat, or on email, or anything)? If it's been publicly announced and at least a week has gone by without pushback, I'll merge it.

2020-10-05 13:55 UTC, lynnbendixsen commented
@dhh1128 I announced it on September 18th on the #indy-contributors channel, but not yet via any other method. I am happy to share with a wider audience if that is the next step. I have not yet gotten any negative comments from anyone or even any questions that could be interpreted as pushback. All has been positive. Thanks!

2020-10-05 15:06 UTC, dhh1128 commented
If you announced it 2 weeks ago, I think it's ready to merg.

2020-10-05 15:12 UTC, merged